### PR TITLE
feat: added system uptime to proc_stats

### PR DESCRIPTION
**Pull request by KwadFan**
Added system uptime to proc_stats.py

This could be handy in case you want to display the uptime of the host or events that relie on time since last reboot.

Signed-off-by: Stephan Wendel <me@stephanwe.de>

### CODE REVIEW

**Comment by Arksine** [comment]
Thanks.  Python has a method for retrieving uptime:

```python
time.clock_gettime(time.CLOCK_BOOTTIME)
```
I don't mind adding support for this and reporting in the response to `/machine/proc_stats`.  I don't think its necessary to add it to the event as its value is predictable once you have a reference.  If a client wants to stream uptime on its UI that can be done at whatever interval a client desires by simply adding time elapsed to the reference.

**Comment by KwadFan** [comment]
Thank you, for your helpful respond.
I started recently with python. Steep learning curve :)

So, I used time instead of proc/uptime file.

Regards

**Comment by KwadFan** [comment]
Hi again,
after some discussion and thinking twice about it, it is ridiculous to "spam" every second its uptime.

So, I have to think about a better place to get the Host boot time.
Therefor that PR should be closed.
Thank you for taking your time :)

**Comment by Arksine** [comment]
No problem. FWIW,I just pushed  9b5b3cc506a6412343047a2887026315e89c1333 which will report `system_uptime` in the response to the `/machine/proc_stats` request.

If you want to continuously update it on the UI you should be able to request that value as the reference or `start_value`, record the local time when you received it, and use that to calculate the time elapsed for each update.  Then just add the time elapse to the initial uptime.

**Pull request closed without merging**
