### PR TITLE
According to #46

### PR DESCRIPTION
**Pull request by KwadFan**
That is not the best solution to force users to use some sudo commands without a password,
but keeps working moonraker flawless with that changes.

### CODE REVIEW

**Comment by KwadFan** [comment]
So, echoing into `/etc/environment` is the simplest solution to serve the Variable across all Distros and user combinations. A better way would modifying the `/etc/skel` related files but they can be differ in many ways, so that it would take much more patience through functions and parsing existing configurations. In that prospective, applying system wide is K.I.S.S prinziple

**Comment by Arksine** [comment]
Thanks.  I'm okay with the changes to sudo_fix.sh and will merge them.  My opinion on the install script remains the same, the fix only applies to CustomPiOS based distros so the fix shouldn't be part of the generic install script.   Users who are running CustomPiOS derived distros should run this script separately.

**Comment by KwadFan** [comment]
Ok, i will change that. Unfortunatly due lack of time, will be tomorrow...

**Comment by Arksine** [comment]
Thanks.  I merged the change to sudo_fix.sh, so you don't need to take any additional action unless you need to further change the sudo_fix script.

**Comment by cadriel** [comment]
@KwadFan

How would you expect the custompios build to introduce the sudo change? Should the moonraker module simply run the new install script, or would a specific new module need to be introduced for this?

**Comment by KwadFan** [comment]
Sorry for being late with the answer. Its a busy time in my main Job so close bevor Christmas :) I think, you could just run sudo_fix.sh in the installation module or in fluiddpi module. Second Method would be my prferred. Put the "cat part" directly into a file and copy over into filesystem section of fluiddpi module, add pi to needed mnrkrsudo group via start_script. If you want I can add a pull request for FluiddPi at Weekend with the changes. I am also sorry for not using the right tags and terms its a mess with german keyboard on Mobilephone :)

**Comment by KwadFan** [comment]
I think we can close this, due your merge. Have nice Christmas Holidays :)

**Pull request closed without merging**
