### PR TITLE
Support Creality Print Slicer generated gcode metadata.

### PR DESCRIPTION
**Pull request by ballaswag**
Most of the code are from Creality's version of moonraker. I removed their thumbnail override and fallback the default. They also originally look for these metadata in the footer which was wrong or changed. Looking for them in the header works now.

Example metascan
```
curl -XPOST localhost:7125/server/files/metascan?filename=piggy_fab_K1_0.4_Hyper\ PLA_1.75_1h29m.gcode | jq .
{
  "result": {
    "size": 7928645,
    "modified": 1697844230.756268,
    "uuid": "7cbcc8b8-2752-40ee-9d18-f635d5bc637d",
    "slicer": "Creality",
    "slicer_version": "4.3.6.6242",
    "gcode_start_byte": 133872,
    "gcode_end_byte": 7928630,
    "layer_count": 409,
    "object_height": 81.8,
    "estimated_time": 5380,
    "layer_height": 0.2,
    "first_layer_height": 0.2,
    "first_layer_extr_temp": 220,
    "first_layer_bed_temp": 45,
    "filament_name": "Hyper PLA_1.75",
    "filament_type": "PLA",
    "filament_total": 20671.199999999997,
    "filament_weight_total": 121.54665599999998,
    "thumbnails": [
      {
        "width": 32,
        "height": 32,
        "size": 1874,
        "relative_path": ".thumbs/piggy_fab_K1_0.4_Hyper PLA_1.75_1h29m-32x32.png"
      },
      {
        "width": 300,
        "height": 300,
        "size": 42965,
        "relative_path": ".thumbs/piggy_fab_K1_0.4_Hyper PLA_1.75_1h29m-300x300.png"
      }
    ],
    "print_start_time": null,
    "job_id": null,
    "filename": "piggy_fab_K1_0.4_Hyper PLA_1.75_1h29m.gcode"
  }
}

```

### CODE REVIEW

**Comment by Arksine** [comment]
Thanks.  Unfortunately Creality continues to claim that the `Creality Print Slicer` is their own "self-developed" software, when it is clear from the metadata that it is a fork of Cura.  They do not give credit to Ultimaker nor are they in compliance with the GPL.  This is in addition to initially claiming that the K1 firmware was their own creation.  It wasn't until the device was rooted and dumped did they admit that they were using modified versions Klipper, Moonraker, Fluidd.  

As such, I will not merge specific support for Creality hardware or software in this repo.

**Comment by ballaswag** [comment]
Fully understand the sentiment. Thanks for looking.

**Comment by cinealfa** [comment]
Has Creality fessed uo yet? There seems to be an awful lot of crediting in the about page for Creality Print.  LOL

**Comment by Arksine** [comment]
They seem to have created a repo for Creality Print and thus far are publishing updates.  One of the issues with Creality is that they will create a repo, publish initial source, then stop updating it while they continue to release new versions.

They are still violating the license for Klipper, Moonraker, and likely other software in the Klipper ecosystem.

**Comment by ballaswag** [comment]
I understand the convenience of just using the Creality ego system, but there are better and truly open alternatives from community, use those instead.

**Pull request closed without merging**
