### PR TITLE
metadata: support multiple filaments length for prusaslicer

### PR DESCRIPTION
**Pull request by bakatrouble**
The metadata parser was unable to parse used filament length when the slicer is set up for MMU, resulting in line 
```; filament used [mm] = 0, 0, 0, 0, 31653.68```

`Signed-off-by: Aleksey Frolov <bakatrouble@gmail.com>`

### CODE REVIEW

**Comment by Arksine** [comment]
Thanks.  The changes look ok, however the commits need to be [signed off](https://moonraker.readthedocs.io/en/latest/contributing/#git-commit-format) before they can be merged.  It is sufficient to add the `Signed-off-by` line to the PR if you don't want to amend the commits themselves.

**Comment by bakatrouble** [comment]
> Thanks. The changes look ok, however the commits need to be [signed off](https://moonraker.readthedocs.io/en/latest/contributing/#git-commit-format) before they can be merged. It is sufficient to add the `Signed-off-by` line to the PR if you don't want to amend the commits themselves.

Added to the pr message

**Comment by Arksine** [comment]
Thanks, however the signature requires your real name, not an alias.

**Comment by bakatrouble** [comment]
Changed

**Comment by Arksine** [comment]
Thanks.

**Pull request merged**
