### PR TITLE
Docs/davidzwa fix docs remote api

### PR DESCRIPTION
**Pull request by davidzwa**
# Motivation 

I have been implementing a Typescript client from the Remote API documentation. In some cases I failed to do so because of:
- wrong url's 
- JSON serialization issues (automatic conversion to Typescript models) due to leading commas

## Changes

These are some tweaks to the documentation:
- consistency with response format: nowhere the "result" wrapper will be shown in the response (to avoid confusion)
- leading commas (achieve JSON serializability)
- wrong url (webcam delete, wled toggle)
- unclosed json section
- spacing:
  - "method":"machine.wled.toggle" 
  - "method": "machine.wled.toggle")

## Tests

I have tested all URL changes. The changes work, whereas the original URLs did not (404 response on Moonraker API).

## Final remarks 

Should not be hard to review!

### CODE REVIEW

**Comment by davidzwa** [comment]
@Arksine Im eager to hear your response!

**Comment by Arksine** [comment]
Thanks.  While the changes look correct, I'm actually in the process of rewriting the entire API documentation, with full schemas and corrected responses.  That said, its a long process and I don't know when it will be ready to merge.  At the moment I have very little free time to complete it.

**Comment by davidzwa** [comment]
No problem. Shall we merge this PR and then I help out with the new docs?

**Comment by Arksine** [comment]
Thanks.  After giving this some thought, I do think its worth merging this now and dealing with the merge conflicts on my local rework branch.

**Pull request merged**
