### PR TITLE
history: added new spool_length value to track filament on a spool

### PR DESCRIPTION
**Pull request by Mascherino**
history: added a spool_length value to job totals to track filament of a spool

docs: added the set_spool_length API

Signed-off-by: Maximilian Schmidt <github@keedosuul.de>

### CODE REVIEW

**Comment by Arksine** [comment]
Thanks.  I don't believe that the `history` module is appropriate for spool tracking, that really needs its own component independent of history.  This is particularly true of `job_totals`, which is intended to track the totals for the life of the printer and shouldn't include individual items that are reset.

**Comment by netweaver1970** [comment]
interesting. With RFID in mind, for a more automated spool identifcation/tracking later on? Almost sounds like a very professional feature :)

**Comment by Mascherino** [comment]
Understandable. Is there a something regarding filament / spool tracking in development?

**Comment by Arksine** [comment]
Sorry, I missed the end of this convo earlier.  I have been in touch with someone working up an updated version of spool tracking, they intent to PR shortly

**Comment by Mascherino** [comment]
I was working on my own version of spool tracking based on the code of PR #123. Guess I can stop if you already have someone working on it?

**Comment by Arksine** [comment]
I believe that [this](https://github.com/Arksine/moonraker/pull/123#issuecomment-1100427994) is who is currently working on a version.  We have discussed it a bit on discord and he indicated that he planned to create a PR soon.

I would leave it up to you as to how you want to proceed.  You could pause your work for a bit and check for the PR if you would like, and you are certainly welcome to add feedback when it is available.

**Comment by Mascherino** [comment]
Would love to get in touch with them and see if they would like to work together on it. As far I saw they based their code on the same source as I did, so a collaboration could be beneficial.

**Pull request closed without merging**
