### PR TITLE
Added ability to control hue device groups in power.py

### PR DESCRIPTION
**Pull request by cmerkle**
Added the ability to control entire Hue device power groups in addition to controlling Hue devices individually. This can be advantageous if you have several Hue lights in the area of the printer that you would like to control all together.

### CODE REVIEW

**Comment by Arksine** [comment]
Thanks.  I'm ok with adding support for "Hue Groups", however this implementation looks like its nearly a direct copy and past of the original hue implementation.  Perhaps rather than creating a new "type" we could add an `is_hue_group` boolean option to the original implementation, then set the url and parse the response based on this option.

Additionally the documentation will need to be updated to reflect changes and additions.

**Comment by cmerkle** [comment]
> Thanks.  I'm ok with adding support for "Hue Groups", however this implementation looks like its nearly a direct copy  of the original hue implementation.  Perhaps rather than creating a new "type" we could add an `is_hue_group` boolean option to the original implementation, then set the url and parse the response based on this option.
> 
> 
> 
> Additionally the documentation will need to be updated to reflect changes and additions.

Yea I was thinking about maybe just adding a config option for the existing hue device called "type" which can be either "light" or "group". I can try to implement that when I get a chance. Am I responsible for updating the docs? Sorry, I'm new to all this, this is my first PR.

**Comment by Arksine** [comment]
Looks good.  The `device_type` needs to be documented, then this will be ready to merge.

**Comment by cmerkle** [comment]
@Arksine Docs have been updated!

**Pull request merged**
