### PR TITLE
server: report deprecated klipper options 

### PR DESCRIPTION
**Pull request by Arksine**
This adds a warning for deprecated options in Klipper to the list of warnings reported in `/server/info`.  The configuration warnings generated by Moonraker have been modified for additional clarity.

Signed-off-by:  Eric Callahan <arksine.code@gmail.com>

### CODE REVIEW

**Comment by meteyou** [comment]
for me it is not necessary that moonraker pull this output and passes it. because it is also available via `printer.configfile.warnings`.

**Comment by Arksine** [comment]
Ok.  I think that is probably the best way to handle it, that way the frontend can make a better decision of how to present it.

What I will do is make sure it is clear that moonraker's config warnings specify that the issue is in moonraker.conf.

**Comment by meteyou** [comment]
yep! thats the reason, why i will use two different panels for moonraker and klipper warnings and different buttons for download moonraker log for moonraker warnings and download klippy.log for klipper warnings and more...

**Comment by Arksine** [comment]
I'm gonna go ahead and close this since we have decided that its better to allow clients handle the warnings directly.

**Pull request closed without merging**
