### PR TITLE
Add TOTP Authorization to moonraker auth. algo

### PR DESCRIPTION
**Pull request by SlimRG**
https://github.com/Arksine/moonraker/issues/842

### CODE REVIEW

**Comment by SlimRG** [comment]
Sorry, git system is new for me...

**Comment by Arksine** [comment]
Thanks.  At this time I don't think support for 2FA is a good candidate for this repo.  Moonraker is not intended to run facing the wan directly.   It may be something I consider in the future, but I think I would prefer adding support for OAuth and allowing the provider to handle 2FA.

If you need to add additional security  and cannot use a VPN I would recommend looking into authentication options provided by reverse proxies, etc.

**Comment by SlimRG** [comment]
We can't use VPN in many countries, such as Russia (if you don't have licence), if we don't want to have problems with law (I had this problems by local WireGuard).
Google Authenticator is used in banking services (I know, as I work there). It's quiet simple and secure way to improve security. 
I have in use some printers and want to connect them from office next to my home. Why you don't want to add this secure layer?

**Comment by Arksine** [comment]
> We can't use VPN in many countries, such as Russia (if you don't have licence), if we don't want to have problems with law (I had this problems by local WireGuard).

I understand.   This is why I suggested [using a reverse proxy](https://stackoverflow.com/questions/72434853/ways-of-authentication-with-nginx)  to provide additional authentication if you want expose Moonraker to the wan.

> I have in use some printers and want to connect them from office next to my home. Why you don't want to add this secure layer?

At this time I don't think 2FA adds significant value to Moonraker.   Moonraker is not  intended to run directly facing the wan.  The overwhelming majority of users will not want to enable 2FA to their local installation, in fact the majority do not even have user authentication enabled.    I have not reviewed your submission in detail, however a cursory glance indicates that it would need significant refactoring before its eligible for merging.   The [contribution guidelines](https://moonraker.readthedocs.io/en/latest/contributing/) need to be followed before I provide a detailed review.

In addition, I think it may be possible to add OpenID/OAuth support which would accomplish a similar goal, with the bonus of allowing users to log in with existing accounts.

> P.S. Localhost is not secure enough too, as lots of people use phone number as wifi pass. Also, MGTS provider sets routers with default pass MGTS98765 and without possiblility to change this password.

Users who don't secure their local network and/or routers would be unlikely to user authentication, much less two factor authentication.  They would have bigger vulnerabilities than anything exposed by Moonraker.

>  As I think, 2FA additional secure layer will be better and simpler way, than using LDAP.

LDAP is already integrated and well tested.

**Pull request closed without merging**
