### PR TITLE
add support for hue devices

### PR DESCRIPTION
**Pull request by olli-t**
power: add support for hue devices
docs: add documentation for new device type

Signed-off-by: Oliver Tetz <olli.codes.some.lines@gmail.com>

### CODE REVIEW

**Comment by olli-t** [comment]
Hello folks,
This is my first time contributing. So please leave Feedback or hints if I do some thing wrong. :)

**Comment by Arksine** [comment]
Thanks.  For some reason the type checker doesnt want to automate.  The changes look ok to me, however we do need to make mypy happy.  There is a syntax error in your annotations.  I'm about to add a review with more details.

**Comment by Arksine** [comment]
On second thought, I'll go ahead and pull this PR and correct the annotations, since there are only a couple that would be problematic.

**Comment by Arksine** [comment]
Ok, I pushed your initial commit in 4d803ec9e59501a4274220b090dcd9daee6bd9fd and applied formatting/type checking fixes to make CI happy in bcb7a55996809e106e1368e3d491e7d7549af812.  It would be a good idea for you to pull master and verify that everything works as exepected.  Thanks.

**Pull request closed without merging**
