### PR TITLE
octoprint_compat: added job status & operation

### PR DESCRIPTION
**Pull request by grantrules**
Added job status & operation to complete compatibility with Cura-OctoPrintPlugin. Used simplyprint.py as a guide.

Signed-off-by: Grant Harding <gharding@gmail.com>

### CODE REVIEW

**Comment by grantrules** [comment]
is there a way to return an HTTP error from an endpoint callback?

**Comment by Arksine** [comment]
Thanks.  The purpose `octoprint_compat` plugin is to present the bare minimum API required for upload functionality.  I'm weary of extending Octoprint compatibility beyond that due to the additional maintenance burden involved.  My preference would be for the Cura plugin to use Moonraker's native API if it wants to implement print monitoring.

**Comment by grantrules** [comment]
If that's the case, I may break it out into a plugin. I may also take a look into forking Cura-OctoPrint. There is a moonraker plugin for cura but it is very far from complete.

**Comment by grantrules** [comment]
There now it's a plugin. Maybe it'll be useful for somebody else, too.

https://github.com/grantrules/moonraker-octoprint-enhanced

**Pull request closed without merging**
