### PR TITLE
Adding support for TPLink Tapo plugs

### PR DESCRIPTION
**Pull request by fsnuxer**
Add support for TPLink Tapo plugs.
Thanks to https://github.com/fishbigger/TapoP100 Library
Disclaimer :  I'm no python coder
Works for me at least ;)

https://github.com/Arksine/moonraker/issues/90

### CODE REVIEW

**Comment by Arksine** [comment]
Thanks.  At the moment I am not accepting contributions to the power plugin that requires dependencies.  I have plans to add support for MQTT integration which should allow Moonraker to interact with nearly all devices like this though a 3rd party.  I also plan to implement a 3rd party plugin interface that will allow users to register their own power modules, with the caveat that the plugin developer will be responsible for maintaining it.

**Comment by fsnuxer** [comment]
Fair enough. (I guess in this case the library used could be included or  copy/pasted since it's very small.)

Another solution (for this plug and other) could be a generic  "external command" system ?
=> call a cli command just with an ON / OFF / STATUS parameter ?
And each and every plug could work without adding a dependency for moonraker - and without requiring an mqtt setup : just an external program/script glue...

**Comment by Arksine** [comment]
If the implementation can be added without the dependency I would be open to merging.  After all, this is how the tplink smartplug implementation works.  We would just need to make sure that the license is compatible and any borrowed code is properly credited.

Given that moonraker provides remote access with the ability to modify your configuration files I am not comfortable with supporting configurable CLI commands.  I suspect that someone will end up implementing it in a 3rd party plugin, however my position will be to discourage it.

**Comment by NpFaith** [comment]
@fsnuxer Can you provide the configuration code? I'm new in the Klipper universe and I have p100 smartplug. Thanks in advance

**Comment by fsnuxer** [comment]
> @fsnuxer Can you provide the configuration code? I'm new in the Klipper universe and I have p100 smartplug. Thanks in advance

Hello. Not sure if the code is still ok since I'm not using it anymore.
( The patch included updated documentation.md  ;) )

[power mytapoplug]
type: tplink_tapo
email: youremailusedwhenyouregisteredtheplug
password: yourpasswordusedwhenyouregisteredtheplug
address: ip.of.the.plug

**Comment by Arksine** [comment]
Moonraker does not currently support Tapo plugs.  As mentioned above, support could be added however it needs to be done without the fishbigger TapoP100 dependency.  I wasn't specific as to the issues with the library, so for clarity I will elaborate:
- The TapoP100 package relies on the `requests` module to make http requests.  These are synchronous/blocking requests and they will block Moonraker's asyncio event loop.  There are numerous ways around this, however the best solution is probably to use Tornado's async http client.
- The package also depends on `pycryptodome`.   This isn't a problem for a Raspberry Pi or common x86 linux distros like Ubuntu as they will have prebuilt wheels.  Many other SBCs running Armbian will need to build the wheel for this package and it would be important to validate that a) the wheel can be built in a timely manner and b) the wheel can be built without any additional dependencies or user intervention.

**Comment by NpFaith** [comment]
@¶Arksine I'm noob in this, it is possible for you to explain with more detail the right way to put moonraker communicating with Tapo P100? I'm enjoying allot Klipper, thanks for the help.

**Comment by NpFaith** [comment]
@fsnuxer thanks for the help

**Comment by Arksine** [comment]
@NpFaith An interested developer would need to write an implementation that accesses the Tapo P100 APIs using asynchronous HTTP requests.  They would need to be familiar with asyncio, Moonraker's component API, and the Tapo P100 API.  Unfortunately I there isn't much more detail I can add, these are items the developer would need to research.  If there are specific implementation questions with regard to Moonraker I would be happy to answer them.

**Comment by NpFaith** [comment]
@Arksine I'm not a programmer, I understand algorithmic logic but I have no knowledge of these languages, as I managed to get it to work through the octoprint I thought that with a few little tricks it would be the same in moonraker. My knowledge is really limited. I don't want to use octoprint because I prefer Fluidd, what I need to be fine-tuned for me is to work with the smartplug tapo p100. What languages ​​do you need to know to be able to make the connection between smartplug and moonraker? Thanks anyway and if I need more help I'll talk to you.

**Comment by Arksine** [comment]
Octoprint very likely has a 3rd party plugin that supports the Tapo P100.  Unfortunately there is no way to trick support into Moonraker if you want the device visible in Fluidd, support must be added to the `power` component, which is what this Pull Request attempted to do.  Moonraker is written Python, specifically targeting CPython 3.7+.

**Comment by julianvolden** [comment]
Hi there, any updates on TPlink Tapo plugs? 

Currently i have a tapo p115 plug i want to use

**Comment by Arksine** [comment]
It should be possible to support Tapo plugs with the `generic` http implementation.   Since Moonraker is no longer accepting HTTP specific implementations I am closing this.  Thanks.

**Pull request closed without merging**
