### PR TITLE
wled: Add extra control for wled effects

### PR DESCRIPTION
**Pull request by richardjm**
For the "Percent" preset the intensity controls the amount of the bar lit up 0-100
Work around issue when preset is re-enabled if sending intensity or speed while no preset is active
Signed-off-by:  Richard Mitchell <richardjm+moonraker@gmail.com>

### CODE REVIEW

**Comment by Arksine** [comment]
Thanks.  It appears to me that this adds a new API and changes the behavior of existing APIs, thus it is also necessary to update the API documentation in accordance with the changes.

**Comment by richardjm** [comment]
Do you mean adding a section into web_api.md? I don't believe existing behaviour should be affected as if the arguments aren't specified they default to the values used previously.

**Comment by Arksine** [comment]
The `/machine/wled/control` appears to be a new endpoint.  With regard to new arguments, even if the default behavior does not change, we do need to document all arguments available to endpoints...otherwise developers will not know they are there.

**Comment by richardjm** [comment]
Well I've the documentation and playing with api I've removed the `control` endpoint but added a `toggle` that was missed before.

**Comment by Arksine** [comment]
Thanks.

**Pull request merged**
